# Generated by Django 3.2.15 on 2022-09-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACT', 'Action'), ('ROM', 'Romantic'), ('HOR', 'Horror')], default='ACT', max_length=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
