# Generated by Django 3.2.15 on 2022-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('ACT', 'Action'), ('ROM', 'Romantic'), ('HOR', 'Horror')], default='ACT', max_length=3, null=True),
        ),
    ]
